name: Run All Installations

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run help command.
      run: |
        curl https://raw.githubusercontent.com/ryuta69/dotfiles/master/install.sh | /bin/bash -s -- --help
    - name: Run initial setup.
      run: |
        curl https://raw.githubusercontent.com/ryuta69/dotfiles/master/install.sh | /bin/bash -s -- --init
    - name: Run all test.
      run: |
        /bin/bash install.sh --force --test --init --all
