name: install_settings

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run help command.
      run: |
        make help
    - name: Install dependencies.
      run: |
        make init
    - name: Install dotfiles.
      run: |
        make allrun_workflow
