name: install dotfiles

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run help command.
      run: |
        ./install.sh --help
    - name: Install dependencies.
      run: |
        mkdir -p ~/.ssh
        mkdir -p ~/work
        mkdir -p ~/.config/nvim
        brew tap homebrew/bundle
        brew install zsh
        sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells'
        sudo chsh -s /usr/local/bin/zsh
        chmod 755 /usr/local/share/zsh
        chmod 755 /usr/local/share/zsh/site-functions
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - name: Install package files.
      run: |
        ./packages/install.zsh --force
    - name: Install dotfiles settings.
      run: |
        ./dotfiles/install.zsh --force
    - name: Install vscode settings.
      run: |
        ./vscode/install.zsh --force --test
    - name: Install macos settings.
      run: |
        ./macos/install.zsh --force --test
